-- MySQL Script generated by MySQL Workbench
-- Wed Jan 22 22:34:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema puntoVenta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema puntoVenta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puntoVenta` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `puntoVenta` ;

-- -----------------------------------------------------
-- Table `puntoVenta`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `estado` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `puntoVenta`.`Categoria` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `puntoVenta`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`Articulo` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `codigo` VARCHAR(50) NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `precio_venta` DECIMAL(11,2) NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `imagen` VARCHAR(100) NULL,
  `estado` BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idArticulo`),
  CONSTRAINT `fk_articulo_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `puntoVenta`.`Categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `codigo_UNIQUE` ON `puntoVenta`.`Articulo` (`codigo` ASC) VISIBLE;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `puntoVenta`.`Articulo` (`nombre` ASC) VISIBLE;

CREATE INDEX `fk_articulo_categoria_idx` ON `puntoVenta`.`Articulo` (`categoria_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `puntoVenta`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `puntoVenta`.`rol` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `puntoVenta`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol_id` INT NOT NULL,
  `nombre` VARCHAR(75) NOT NULL,
  `tipo_documento` VARCHAR(25) NULL,
  `num_documetno` VARCHAR(25) NULL,
  `direccion` VARCHAR(150) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(100) NOT NULL,
  `clave` VARCHAR(128) NOT NULL,
  `activo` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `puntoVenta`.`rol` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `puntoVenta`.`usuario` (`nombre` ASC) VISIBLE;

CREATE INDEX `fk_usuario_rol_idx` ON `puntoVenta`.`usuario` (`rol_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `puntoVenta`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(75) NOT NULL,
  `tipo_documento` VARCHAR(25) NULL,
  `num_documetno` VARCHAR(25) NULL,
  `direccion` VARCHAR(150) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `activo` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `puntoVenta`.`persona` (`nombre` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `puntoVenta`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`ingreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `tipoComprobante` VARCHAR(30) NOT NULL,
  `serie_comprobante` VARCHAR(10) NULL,
  `numero_comprobante` VARCHAR(410) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'Aceptado',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ingreso_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `puntoVenta`.`persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fkingreso_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `puntoVenta`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ingreso_persona_idx` ON `puntoVenta`.`ingreso` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fkingreso_usuario_idx` ON `puntoVenta`.`ingreso` (`usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `puntoVenta`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`detalle_ingreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingreso_id` INT NOT NULL,
  `articulo_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_detalleIngreso_ingreso`
    FOREIGN KEY (`ingreso_id`)
    REFERENCES `puntoVenta`.`ingreso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleIngreso_articulo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `puntoVenta`.`Articulo` (`idArticulo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalleIngreso_ingreso_idx` ON `puntoVenta`.`detalle_ingreso` (`ingreso_id` ASC) VISIBLE;

CREATE INDEX `fk_detalleIngreso_articulo_idx` ON `puntoVenta`.`detalle_ingreso` (`articulo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `puntoVenta`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `tipoComprobante` VARCHAR(30) NOT NULL,
  `serie_comprobante` VARCHAR(10) NULL,
  `numero_comprobante` VARCHAR(410) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'Aceptado',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_iventa_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `puntoVenta`.`persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fki_venta_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `puntoVenta`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ingreso_persona_idx` ON `puntoVenta`.`venta` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fkingreso_usuario_idx` ON `puntoVenta`.`venta` (`usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `puntoVenta`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puntoVenta`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `articulo_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `Descuento` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_detalleVenta_vanta`
    FOREIGN KEY (`venta_id`)
    REFERENCES `puntoVenta`.`venta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleVenta_articulo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `puntoVenta`.`Articulo` (`idArticulo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalle_vanta_idx` ON `puntoVenta`.`detalle_venta` (`venta_id` ASC) VISIBLE;

CREATE INDEX `fk_detalleVenta_articulo_idx` ON `puntoVenta`.`detalle_venta` (`articulo_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;